### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by kamushadenes** [2mb-solutions/fleacollar#1]
Hey!

I stumbled with this repository on [this Gist](https://gist.github.com/miguelmota/9456162) and I wonder what is the project state and if you need help with it.

**Comment by stormdragon2976** [comment]
Howdy,
It is pretty much in a working state. Help is always welcome, with new functionality, testing, finding bugs, fixing them, etc.
Interestingly, I used the script to generate my current configuration, but a friend is having trouble with it. So, I'm hunting bugs currently.
